#!/bin/bash

# compile
gcc src/* -o juliatraceable -I inc -lm -DH=$1 -DITNUM=$2

# execute
./juliatraceable $@

# show the resultant image
eog juliatraceable.png

# print dividing line across the length of the terminal
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
